pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
               git 'https://github.com/tkibnyusuf/opedinas-project.git'
            }
        }
       stage('Build') {
            steps {
               sh ''' cd MywebApp && mvn clean package'''
            }
        }
      stage('Test') {
            steps {
                sh ' cd MywebApp && mvn test'

            }
      }          
                
      stage('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: 'f9125a90-ceb2-42b2-9a00-15b4ed9f1198', path: '', url: 'http://52.204.162.226:8080/')], contextPath: 'webapp', war: '**/*.war'
                
            }   
                
      }        
                
    }
}   
