pipeline {
    agent any
    
    stages {
        stage('Git checkout') {
            steps {
                git 'https://github.com/evadox/opedinas-project.git'
            } 
        }
       stage('Mvn Build') {
            steps {
               sh 'cd MywebApp && mvn clean package'
            }
        }
      stage('Mvn Test') {
            steps {
                sh 'cd MywebApp && mvn test'
            }
        }
      stage ('Code Qualty Scan') {
           steps {
                  withSonarQubeEnv('sonarserver') {
             sh "mvn -f MywebApp/pom.xml sonar:sonar"
                      
               }
            }
       }
      stage('deploy to tomcat') {
        steps {
            deploy adapters: [tomcat9(credentialsId: '55c240b0-3172-4a92-948f-d3677469d6c6', path: '', url: 'http://34.238.52.253:8080/')], contextPath: 'tomtom', war: '**/*.war'

        }

    }

   } 
}
