pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
                git 'https://github.com/evadox/opedinas-project.git'
            }
        }
      stage('Build') {
            steps {
               sh ''' cd MywebApp && mvn clean package'''
            }
        }
      stage('Test') {
            steps {
                sh ' cd MywebApp && mvn test'
            }
        }

    
        stage ('Code Qualty Scan') {
            
           steps {
                  withSonarQubeEnv('sonarqube') {
             sh "mvn -f MywebApp/pom.xml sonar:sonar"
                      
               }
            }
       }
     
        
        stage('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: '570c1e3c-b541-42e2-9279-c15819f26c22', path: '', url: 'http://34.238.52.253:8080/')], contextPath: 'mysonar', war: '**/*.war'
            }    
        }    
     }
 }
